---

spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 9002
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: claim
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/